### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by sieumap43** [alanzty/MO3TR#1]
Hi. Thanks very much for the good work.
I was trying to run `python run/train_track_nf.py` and encountered this error

```
Traceback (most recent call last):
  File "run/train_track_nf.py", line 14, in <module>
    from mmdet.apis import set_random_seed
  File "/lhome/MO3TR/moter_py37_venv/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/lhome/MO3TR/moter_py37_venv/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/lhome/MO3TR/moter_py37_venv/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/lhome/MO3TR/moter_py37_venv/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/lhome/MO3TR/moter_py37_venv/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

I have installed the packages and ran `bash setup` as required.
My specs

- Ubuntu 20.04
- Python 3.7.5
- PyTorch 1.9.1+cu102

**Comment by sieumap43** [comment]
Solved by running
```
python3.7 -m venv moter_venv
source moter_venv/bin/activate
pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -U cmake

pip install torch==1.7.1
pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7/index.html
pip install mmcv==1.4.2
pip install mmdet==2.19.0
pip isntall mmtrack==0.8.0
pip install torchvision==0.8.2

bash setup
pip install terminaltables seaborn motmetrics six pycocotools mmcls lap debupy tqdm
```
